<?xml version="1.0" encoding="UTF-8"?><testrun name="StringBufferUtilTest2" project="StringBufferUtilProject" tests="5" started="5" failures="1" errors="0" ignored="0">
  <testsuite name="com.org.test.StringBufferUtilTest2" time="0.0">
    <testcase name="appendTestValid" classname="com.org.test.StringBufferUtilTest2" time="0.0">
      <failure>junit.framework.AssertionFailedError: expected:&lt;Hihallow&gt; but was:&lt;Hihallow&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:50)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:287)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:67)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:74)&#13;
	at com.org.test.StringBufferUtilTest2.appendTestValid(StringBufferUtilTest2.java:18)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="appendTestNull" classname="com.org.test.StringBufferUtilTest2" time="0.0"/>
    <testcase name="appendTestEmpty" classname="com.org.test.StringBufferUtilTest2" time="0.0"/>
    <testcase name="appendTestContructor" classname="com.org.test.StringBufferUtilTest2" time="0.0"/>
    <testcase name="appendTestInBetweenNullCheck" classname="com.org.test.StringBufferUtilTest2" time="0.0"/>
  </testsuite>
</testrun>
